version: '3.8'

services:
  api:
    build:
      context: FiapTechChallenge1\FiapTechChallengeApi
      dockerfile: Dockerfile
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=MyDatabase;User=sa;Password=Your_password123;
    ports:
      - "8000:8080"
    depends_on:
      - db

  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql

volumes:
  mssql_data: