apiVersion: v1
kind: Service
metadata:
  name: sql-server
  namespace: fiaptechchallenge
spec:
  type: NodePort
  selector:
    app: sql-server
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433
      nodePort: 30010