apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sql-data-pvc
  namespace: fiaptechchallenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100mb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data-pvc
  namespace: fiaptechchallenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100mb
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data-pvc
  namespace: fiaptechchallenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100mb
