apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  namespace: fiaptechchallenge
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus:9090
        isDefault: true
        access: proxy
        editable: true
