apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: fiaptechchallenge
spec:
  selector:
    app: grafana

  type: NodePort
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30007