apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: fiaptechchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: /etc/prometheus
              name: prometheus-storage
      volumes:
        - name: prometheus-storage
          persistentVolumeClaim:
            claimName: prom-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: fiaptechchallenge
spec:
  selector:
    app: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
