apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: fiaptechchallenge
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 10s
      evaluation_interval: 15s

    alerting:
      alertmanagers:
        - static_configs:
            - targets: [ ]
          scheme: http
          timeout: 10s
          api_version: v1

    scrape_configs:
      - job_name: prometheus
        honor_timestamps: true
        scrape_interval: 15s
        scrape_timeout: 10s
        metrics_path: /metrics
        scheme: http
        static_configs:
          - targets:
              - localhost:9090

      - job_name: 'api_dotnet-consumer-api'
        scrape_interval: 5s  # Intervalo de coleta para este job específico
        static_configs:
          - targets:
              - backend-api-consumer:4000

      - job_name: 'api_dotnet-consumer'
        scrape_interval: 5s  # Intervalo de coleta para este job específico
        static_configs:
          - targets:
              - backend-worker-consumer:4002

      - job_name: 'api_dotnet-producer'
        scrape_interval: 5s  # Intervalo de coleta para este job específico
        static_configs:
          - targets:
              - backend-api-producer:4001

      - job_name: 'rabbitmq'
        static_configs:
          - targets:
              - rabbitmq:15692
