apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-worker-consumer
  namespace: fiaptechchallenge
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-worker-consumer
  template:
    metadata:
      labels:
        app: backend-worker-consumer
    spec:
      imagePullSecrets:
        - name: dockerhub-secret
      containers:
        - name: backend-worker-consumer
          image: heiterpm/fiaptechchallenge-consumer:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 4002
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: "Production"
