services:
 
  backend_worker_consumer:
    build:
      dockerfile: ./FiapTechChallenge.Consumer/Dockerfile
    container_name: FiapTechChallenge.Worker_Consumer
    depends_on:
        - sql_server
 
  backend_api_producer:
    build:
      dockerfile: ./FiapTechChallenge.Producer/Dockerfile
    container_name: FiapTechChallenge.API_Producer
    ports:
      - "4001:4001"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:4001"
      MicrosoftSQLServer__ConnectionString: "Server=sql_server;Database=TechChallenge;User Id=sa;Password=SqlServer2019!;TrustServerCertificate=True;"
    depends_on:
        - sql_server

  backend_api:
    build:
      dockerfile: ./FiapTechChallenge.API/Dockerfile
    container_name: FiapTechChallenge.API
    ports:
      - "4000:4000"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://*:4000"
      MicrosoftSQLServer__ConnectionString: "Server=sql_server;Database=TechChallenge;User Id=sa;Password=SqlServer2019!;TrustServerCertificate=True;"
    depends_on:
        - sql_server

  sql_server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sql_server
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1444:1433"
    volumes:
      - sql_data:/var/opt/mssql

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus-grafana/prometheus:/etc/prometheus
      - prom_data:/prometheus

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./prometheus-grafana/grafana:/etc/grafana/provisioning/datasources

  rabbitmq:
    image: masstransit/rabbitmq 
    container_name: rabbitmq
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  sql_data:
  prom_data:
  rabbitmq_data:  