kubectl apply -f ./k8s/backend/backend-api-consumer-deployment.yml
kubectl apply -f ./k8s/backend/backend-api-consumer-service.yml
kubectl apply -f ./k8s/backend/backend-api-producer-deployment.yml
kubectl apply -f ./k8s/backend/backend-api-producer-service.yml
kubectl apply -f ./k8s/backend/backend-worker-consumer-deployment.yml
kubectl apply -f ./k8s/backend/backend-worker-consumer-service.yml
kubectl apply -f ./k8s/banco/sql-server-deployment.yml
kubectl apply -f ./k8s/banco/sql-server-service.yml
kubectl apply -f ./k8s/monitoramento/grafana-configmap.yml
kubectl apply -f ./k8s/monitoramento/grafana-deployment.yml
kubectl apply -f ./k8s/monitoramento/grafana-service.yml
kubectl apply -f ./k8s/monitoramento/prometheus-configmap.yml
kubectl apply -f ./k8s/monitoramento/prometheus-deployment.yml
kubectl apply -f ./k8s/monitoramento/prometheus-service.yml
kubectl apply -f ./k8s/rabbit/rabbitmq-deployment.yml
kubectl apply -f ./k8s/rabbit/rabbitmq-service.yml
kubectl apply -f ./k8s/namespace.yml
kubectl apply -f ./k8s/volume-persistentvolumeclaim.yml
