apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fiaptechchallenge
spec:
  selector:
    app: rabbitmq
  ports:
    - name: rabbitmq-port
      port: 5672
      targetPort: 5672
    - name: rabbitmq-management
      port: 15672
      targetPort: 15672
      nodePort: 30003
    - name: rabbitmq-heartbeat
      port: 15692
      targetPort: 15692
  type: NodePort