apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fiaptechchallenge
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:management
          ports:
            - containerPort: 15672  # Porta da interface de gerenciamento
            - containerPort: 5672    # Porta de comunicação padrão
            - containerPort: 15692   # Porta de métricas Prometheus
          env:
            - name: RABBITMQ_DEFAULT_USER
              value: "guest"
            - name: RABBITMQ_DEFAULT_PASS
              value: "guest"
          volumeMounts:
            - mountPath: /var/lib/rabbitmq
              name: rabbitmq-storage
          command:
            - "sh"
            - "-c"
            - "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
      volumes:
        - name: rabbitmq-storage
          persistentVolumeClaim:
            claimName: rabbitmq-data-pvc
